### ISSUE TITLE
ImportError after setup

### ISSUE THREAD

**Issue by polrodoreda** [mlavin/django-selectable#196]
After setup using readthedocs, when I execute runserver I obtain:

```bash
Unhandled exception in thread started by <function wrapper at 0x7fba2e55e230>
Traceback (most recent call last):
  File "/home/polrodoreda/Documents/DjangoCity/venv/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/polrodoreda/Documents/DjangoCity/venv/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "/home/polrodoreda/Documents/DjangoCity/venv/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 251, in raise_last_exception
    six.reraise(*_exception)
  File "/home/polrodoreda/Documents/DjangoCity/venv/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/polrodoreda/Documents/DjangoCity/venv/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/polrodoreda/Documents/DjangoCity/venv/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/polrodoreda/Documents/DjangoCity/venv/local/lib/python2.7/site-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named smart_selectsselectable
```

**Comment by mlavin** [comment]
From the error it looks like you have `smart_selectsselectable` in your `INSTALLED_APPS`. Maybe you are missing a comma?
